services:
  - type: web
    name: niti-setu-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: CLIENT_ORIGIN
        value: "*"
